In [1]:
import os
import matplotlib.pyplot as plt
!pip install joblib
import joblib
import numpy as np
plt.style.use("fivethirtyeight")

  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)


In [8]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights=np.random.randn(3)*1e-4
        self.eta=eta#learning rate
        self.epochs=epochs#iteration
    def fit(self, X, y):
        self.X=X
        self.y=y
        
        X_with_bias=np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")

In [11]:
obj=Perceptron(eta=0.01, epochs=10)

In [12]:
obj.eta

0.01

In [13]:
obj.epochs

10

In [15]:
obj.fit(X,y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [14]:
y=np.ones((4,1))

In [3]:
-np.ones((4,1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [4]:
X=np.ones((4,2))

In [5]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
np.c_[X, -np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])