In [16]:
import os
import matplotlib.pyplot as plt
!pip install joblib
import joblib
import numpy as np
import pandas as pd
plt.style.use("fivethirtyeight")

In [45]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights=np.random.randn(3)*1e-4
        self.eta=eta#learning rate
        self.epochs=epochs#iteration
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    def activation_function(self,z):
        return np.where(z > 0, 1, 0)
    def fit(self, X, y):
        self.X=X
        self.y=y
        
        X_with_bias=np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >>{epoch +1}")
            print("--"*10)
            
            z=self._z_outcome(X_with_bias, self.weights)
            y_hat=self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            self.error=self.y-y_hat
            print(f"error: \n{self.error}")
            self.weights=self.weights+self.eta*np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch +1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
    def predict(self, X):
        X_with_bias=np.c_[X, -np.ones((len(X),1))]
        z=self._z_outcome(X_with_bias,self.weights)
        return self.activation_function(z)

In [46]:
OR={"x1":[0,0,1,1],
   "X2":[0,1,0,1],
   "y":[0,1,1,1]
   }
df_OR=pd.DataFrame(OR)

In [47]:
df_OR

x1  X2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [48]:
def prepare_data(df, target_col='y'):
    X=df.drop(target_col,axis=1)
    y=df[target_col]
    return X,y

In [49]:
X,y=prepare_data(df_OR)
ETA=0.1
EPOCHS=10
model_or=Perceptron(eta=ETA, epochs=EPOCHS)
model_or.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >>1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-1.07255407e-05  1.06930821e-04  9.99802702e-02]
####################
--------------------
for epoch >>2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.19998927  0.20010693 -0.20001973]
####################
--------------------
for epoch >>3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 0.19998927  0.20010693 -0.10001973]
####################
--------------------
for epoch >>4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: 

In [39]:
model_or.predict(X=[[0,1]])

array([1])

In [24]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [4]:
X=np.ones((4,2))

In [5]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
np.c_[X, -np.ones((4,1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])